# Generated by Django 3.1.7 on 2021-06-02 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email_is_verifyed',
            new_name='email_is_verified',
        ),
    ]
