# Generated by Django 3.1.7 on 2021-06-03 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_wallet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
